Repository acromat1c/DTE2604, pull requests merged in 2025-05, with the labels that each got.

#47 Feature/friend-requests-page
  app/programmingCourse/models_io.py
  app/programmingCourse/urls.py
  app/programmingCourse/views.py
  app/templates/programmingCourse/friend.html
  app/templates/programmingCourse/friend_list.html
  app/templates/programmingCourse/friend_requests.html
  app/templates/programmingCourse/index.html
  app/templates/programmingCourse/test.html
Labels: feature

#54 chore: new images for booster items
  app/media/item_pic/luck_booster.png
  app/media/item_pic/power_booster.png
  app/media/item_pic/speed_booster.png
  app/media/item_pic/xp_booster.png
Labels: chore

#57 moved gacha button to shop. fixed spelling
  app/programmingCourse/urls.py
  app/templates/programmingCourse/gatcha.html
  app/templates/programmingCourse/main.html
  app/templates/programmingCourse/shop.html
  setup.py
Labels: chore

#51 Profile border and title
  app/fixtures/initial_items_content.json
  app/media/item_pic/bronze_border.png
  app/media/item_pic/gold_border.png
  app/media/item_pic/no_border.png
  app/media/item_pic/rainbow_border.png
  app/media/item_pic/silver_border.png
  app/programmingCourse/migrations/0002_profile_border_profile_title.py
  app/programmingCourse/models.py
  app/programmingCourse/models_io.py
  app/programmingCourse/urls.py
  app/programmingCourse/views.py
  app/static/programmingCourse/static.css
  app/templates/base.html
  app/templates/programmingCourse/course.html
  app/templates/programmingCourse/courses.html
  app/templates/programmingCourse/friend_list.html
  app/templates/programmingCourse/friend_requests.html
  app/templates/programmingCourse/friend_search.html
  app/templates/programmingCourse/group_settings.html
  app/templates/programmingCourse/inventory.html
  app/templates/programmingCourse/main.html
  app/templates/programmingCourse/shop.html
  app/templates/programmingCourse/user.html
Labels: feature, bugfix

#58 merge migrations
  app/programmingCourse/migrations/0001_initial.py
  app/programmingCourse/migrations/0002_profile_border_profile_title.py
  app/programmingCourse/migrations/0002_profile_current_course.py
  app/programmingCourse/models.py
Labels: chore

#44 laget en intern leaderboard for grupper
  app/programmingCourse/models_io.py
Labels: feature

#64 fix profile pics on friend requests page
  app/templates/programmingCourse/friend_requests.html
Labels: bugfix
